FROM node:10-alpine

# install and cache app dependencies
COPY package.json /app/package.json

WORKDIR /app

#Install dependencies
RUN npm install boardgame.io
RUN npm install node-persist
RUN npm i esm

COPY src/server.js /app/server.js
COPY src/game/PAFF.js /app/game/PAFF.js
EXPOSE 8000
CMD ["node", "-r", "esm", "/app/server.js"]


