version: '3.3'

services:

  webapp:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'

  board-server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

