version: '3.3'

services:

  webapp:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

  server:
    restart: unless-stopped
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: Dockerfile-server

