version: "3.3"

services:
  webapp:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:81:80"

  server:
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    build:
      context: .
      dockerfile: Dockerfile-server
